source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'pact', path: '../../'
  gem 'pact_broker-client', '>= 1.51.2'
  gem 'pry'
end

gem 'rake'
gem 'rack', '~>2.2'
gem 'httparty'
